name: community_islamic_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.7+13

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_qiblah: ^3.0.4
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  intl: 
  http: ^1.2.2
  animated_notch_bottom_bar: ^1.0.3
  url_launcher: ^6.3.0
  # flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.3.0
  # firebase_messaging: ^15.0.4
  app_settings: ^5.1.1
  firebase_database: ^11.0.4
  uuid: ^4.4.2
  firebase_analytics: ^11.2.1
  cloud_firestore: ^5.2.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5
  flutter_easyloading: ^3.0.5
  auto_scroll_text: ^0.0.7
  islamic_hijri_calendar:
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2
  overlay_loader_with_app_icon: ^0.0.4
  flutter_spinkit: ^5.2.1
  flutter_html: ^3.0.0-beta.2
  hijri: ^3.0.0
  jhijri: ^1.0.0
  blinking_text: ^1.0.4
  carousel_slider: ^5.0.0
  share_plus: ^10.1.3
  video_player: ^2.9.2
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.1
  audio_service: ^0.18.17
  audioplayers: ^6.1.2
  just_audio: ^0.9.46
  flutter_linkify: ^6.0.0
  firebase_messaging: ^15.2.4
  awesome_notifications_core: 
  awesome_notifications: 
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_icon/
    - assets/splash_icon/
    - assets/images/
    - assets/services_icons/
    - assets/icons/
    - assets/ConnectIcons/
    - assets/video/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JameelNori1
      fonts:
        - asset: assets/fonts/jameelNori1.ttf
    - family: JameelNori2
      fonts:
        - asset: assets/fonts/jameelNori2.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
